version: '3'
services:
  mysql:
    image: mysql:8 # 指定镜像
    container_name: hicode-mysql # 指定容器名
    environment:
      MYSQL_ROOT_PASSWORD: 261615 # 指定root密码
    ports:
      - "3306:3306" # 指定端口映射
    volumes:
      - ./mysql-data:/var/lib/mysql # 指定数据卷
      - ./mysql-init:/docker-entrypoint-initdb.d # 指定初始化脚本
    restart: always # 指定重启策略
    networks:
      - hicode-network # 指定网络
  redis:
    image: redis:6 # 指定镜像
    container_name: hicode-redis # 指定容器名
    ports:
      - "6379:6379" # 指定端口映射
    networks:
      - hicode-network # 指定网络
    volumes:
      - ./.redis-data:/data # 指定数据卷
  hicode-backend:
    container_name: hicode-backend
    build: # 服务的Docker构建文件位置
        context: ./
        dockerfile: Dockerfile
    ports:
        - "8101:8101"
    networks:
        - hicode-network
    depends_on:
        - mysql
        - redis
networks:
  hicode-network: